name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    uses: apidepth-io/apidepth-tooling/.github/workflows/lint-ruby.yml@main
    with:
      ruby-version: "3.2"
